- name: Install MySQL Client
  ansible.builtin.yum:
    name: mysql
    state: installed

- name: Load Schema
  ansible.builtin.shell: mysql -h mysql.rdevops57online.com -uroot -pRoboshop@1 < /app/schema/{{component}}.sql
